#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BGABANKUltimate")]
public partial class BGABANKUltimateDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertkartlar(kartlar instance);
  partial void Updatekartlar(kartlar instance);
  partial void Deletekartlar(kartlar instance);
  partial void Insertkredi_istek(kredi_istek instance);
  partial void Updatekredi_istek(kredi_istek instance);
  partial void Deletekredi_istek(kredi_istek instance);
  partial void Insertsubeler(subeler instance);
  partial void Updatesubeler(subeler instance);
  partial void Deletesubeler(subeler instance);
  partial void Inserthareketler(hareketler instance);
  partial void Updatehareketler(hareketler instance);
  partial void Deletehareketler(hareketler instance);
  partial void Insertiletisim_formu_mesajlari(iletisim_formu_mesajlari instance);
  partial void Updateiletisim_formu_mesajlari(iletisim_formu_mesajlari instance);
  partial void Deleteiletisim_formu_mesajlari(iletisim_formu_mesajlari instance);
  partial void Insertayarlar(ayarlar instance);
  partial void Updateayarlar(ayarlar instance);
  partial void Deleteayarlar(ayarlar instance);
  partial void InsertIP(IP instance);
  partial void UpdateIP(IP instance);
  partial void DeleteIP(IP instance);
  partial void Insertgirisler(girisler instance);
  partial void Updategirisler(girisler instance);
  partial void Deletegirisler(girisler instance);
  partial void Insertmusteri(musteri instance);
  partial void Updatemusteri(musteri instance);
  partial void Deletemusteri(musteri instance);
  #endregion
	
	public BGABANKUltimateDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BGABANKUltimateConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BGABANKUltimateDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BGABANKUltimateDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BGABANKUltimateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BGABANKUltimateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<haberler> haberlers
	{
		get
		{
			return this.GetTable<haberler>();
		}
	}
	
	public System.Data.Linq.Table<kartlar> kartlars
	{
		get
		{
			return this.GetTable<kartlar>();
		}
	}
	
	public System.Data.Linq.Table<kredi_istek> kredi_isteks
	{
		get
		{
			return this.GetTable<kredi_istek>();
		}
	}
	
	public System.Data.Linq.Table<subeler> subelers
	{
		get
		{
			return this.GetTable<subeler>();
		}
	}
	
	public System.Data.Linq.Table<hareketler> hareketlers
	{
		get
		{
			return this.GetTable<hareketler>();
		}
	}
	
	public System.Data.Linq.Table<iletisim_formu_mesajlari> iletisim_formu_mesajlaris
	{
		get
		{
			return this.GetTable<iletisim_formu_mesajlari>();
		}
	}
	
	public System.Data.Linq.Table<ayarlar> ayarlars
	{
		get
		{
			return this.GetTable<ayarlar>();
		}
	}
	
	public System.Data.Linq.Table<IP> IPs
	{
		get
		{
			return this.GetTable<IP>();
		}
	}
	
	public System.Data.Linq.Table<girisler> girislers
	{
		get
		{
			return this.GetTable<girisler>();
		}
	}
	
	public System.Data.Linq.Table<musteri> musteris
	{
		get
		{
			return this.GetTable<musteri>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.haberler")]
public partial class haberler
{
	
	private int _id;
	
	private string _haber_baslik;
	
	private string _haber_detay;
	
	private string _haber_foto_link;
	
	private string _haber_link;
	
	private string _haber_foto_yol;
	
	public haberler()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haber_baslik", DbType="NVarChar(150)")]
	public string haber_baslik
	{
		get
		{
			return this._haber_baslik;
		}
		set
		{
			if ((this._haber_baslik != value))
			{
				this._haber_baslik = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haber_detay", DbType="NVarChar(MAX)")]
	public string haber_detay
	{
		get
		{
			return this._haber_detay;
		}
		set
		{
			if ((this._haber_detay != value))
			{
				this._haber_detay = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haber_foto_link", DbType="VarChar(MAX)")]
	public string haber_foto_link
	{
		get
		{
			return this._haber_foto_link;
		}
		set
		{
			if ((this._haber_foto_link != value))
			{
				this._haber_foto_link = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haber_link", DbType="VarChar(MAX)")]
	public string haber_link
	{
		get
		{
			return this._haber_link;
		}
		set
		{
			if ((this._haber_link != value))
			{
				this._haber_link = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haber_foto_yol", DbType="NVarChar(150)")]
	public string haber_foto_yol
	{
		get
		{
			return this._haber_foto_yol;
		}
		set
		{
			if ((this._haber_foto_yol != value))
			{
				this._haber_foto_yol = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kartlar")]
public partial class kartlar : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _k_id;
	
	private System.Nullable<int> _mid;
	
	private string _numara;
	
	private string _sifre;
	
	private System.Nullable<int> _cvc;
	
	private System.Nullable<System.DateTime> _bitis_tarihi;
	
	private System.Nullable<System.DateTime> _alim_tarihi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onk_idChanging(int value);
    partial void Onk_idChanged();
    partial void OnmidChanging(System.Nullable<int> value);
    partial void OnmidChanged();
    partial void OnnumaraChanging(string value);
    partial void OnnumaraChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OncvcChanging(System.Nullable<int> value);
    partial void OncvcChanged();
    partial void Onbitis_tarihiChanging(System.Nullable<System.DateTime> value);
    partial void Onbitis_tarihiChanged();
    partial void Onalim_tarihiChanging(System.Nullable<System.DateTime> value);
    partial void Onalim_tarihiChanged();
    #endregion
	
	public kartlar()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int k_id
	{
		get
		{
			return this._k_id;
		}
		set
		{
			if ((this._k_id != value))
			{
				this.Onk_idChanging(value);
				this.SendPropertyChanging();
				this._k_id = value;
				this.SendPropertyChanged("k_id");
				this.Onk_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mid", DbType="Int")]
	public System.Nullable<int> mid
	{
		get
		{
			return this._mid;
		}
		set
		{
			if ((this._mid != value))
			{
				this.OnmidChanging(value);
				this.SendPropertyChanging();
				this._mid = value;
				this.SendPropertyChanged("mid");
				this.OnmidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numara", DbType="NVarChar(50)")]
	public string numara
	{
		get
		{
			return this._numara;
		}
		set
		{
			if ((this._numara != value))
			{
				this.OnnumaraChanging(value);
				this.SendPropertyChanging();
				this._numara = value;
				this.SendPropertyChanged("numara");
				this.OnnumaraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(32)")]
	public string sifre
	{
		get
		{
			return this._sifre;
		}
		set
		{
			if ((this._sifre != value))
			{
				this.OnsifreChanging(value);
				this.SendPropertyChanging();
				this._sifre = value;
				this.SendPropertyChanged("sifre");
				this.OnsifreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvc", DbType="Int")]
	public System.Nullable<int> cvc
	{
		get
		{
			return this._cvc;
		}
		set
		{
			if ((this._cvc != value))
			{
				this.OncvcChanging(value);
				this.SendPropertyChanging();
				this._cvc = value;
				this.SendPropertyChanged("cvc");
				this.OncvcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitis_tarihi", DbType="DateTime")]
	public System.Nullable<System.DateTime> bitis_tarihi
	{
		get
		{
			return this._bitis_tarihi;
		}
		set
		{
			if ((this._bitis_tarihi != value))
			{
				this.Onbitis_tarihiChanging(value);
				this.SendPropertyChanging();
				this._bitis_tarihi = value;
				this.SendPropertyChanged("bitis_tarihi");
				this.Onbitis_tarihiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alim_tarihi", DbType="DateTime")]
	public System.Nullable<System.DateTime> alim_tarihi
	{
		get
		{
			return this._alim_tarihi;
		}
		set
		{
			if ((this._alim_tarihi != value))
			{
				this.Onalim_tarihiChanging(value);
				this.SendPropertyChanging();
				this._alim_tarihi = value;
				this.SendPropertyChanged("alim_tarihi");
				this.Onalim_tarihiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kredi_istek")]
public partial class kredi_istek : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _kre_id;
	
	private System.Nullable<int> _mid;
	
	private string _miktar;
	
	private string _mesaj;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkre_idChanging(int value);
    partial void Onkre_idChanged();
    partial void OnmidChanging(System.Nullable<int> value);
    partial void OnmidChanged();
    partial void OnmiktarChanging(string value);
    partial void OnmiktarChanged();
    partial void OnmesajChanging(string value);
    partial void OnmesajChanged();
    #endregion
	
	public kredi_istek()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kre_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int kre_id
	{
		get
		{
			return this._kre_id;
		}
		set
		{
			if ((this._kre_id != value))
			{
				this.Onkre_idChanging(value);
				this.SendPropertyChanging();
				this._kre_id = value;
				this.SendPropertyChanged("kre_id");
				this.Onkre_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mid", DbType="Int")]
	public System.Nullable<int> mid
	{
		get
		{
			return this._mid;
		}
		set
		{
			if ((this._mid != value))
			{
				this.OnmidChanging(value);
				this.SendPropertyChanging();
				this._mid = value;
				this.SendPropertyChanged("mid");
				this.OnmidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miktar", DbType="NVarChar(50)")]
	public string miktar
	{
		get
		{
			return this._miktar;
		}
		set
		{
			if ((this._miktar != value))
			{
				this.OnmiktarChanging(value);
				this.SendPropertyChanging();
				this._miktar = value;
				this.SendPropertyChanged("miktar");
				this.OnmiktarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesaj", DbType="NVarChar(50)")]
	public string mesaj
	{
		get
		{
			return this._mesaj;
		}
		set
		{
			if ((this._mesaj != value))
			{
				this.OnmesajChanging(value);
				this.SendPropertyChanging();
				this._mesaj = value;
				this.SendPropertyChanged("mesaj");
				this.OnmesajChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.subeler")]
public partial class subeler : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _s_id;
	
	private string _ad;
	
	private string _adres;
	
	private string _tip;
	
	private string _durum;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ons_idChanging(int value);
    partial void Ons_idChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void OntipChanging(string value);
    partial void OntipChanged();
    partial void OndurumChanging(string value);
    partial void OndurumChanged();
    #endregion
	
	public subeler()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int s_id
	{
		get
		{
			return this._s_id;
		}
		set
		{
			if ((this._s_id != value))
			{
				this.Ons_idChanging(value);
				this.SendPropertyChanging();
				this._s_id = value;
				this.SendPropertyChanged("s_id");
				this.Ons_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50)")]
	public string ad
	{
		get
		{
			return this._ad;
		}
		set
		{
			if ((this._ad != value))
			{
				this.OnadChanging(value);
				this.SendPropertyChanging();
				this._ad = value;
				this.SendPropertyChanged("ad");
				this.OnadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(50)")]
	public string adres
	{
		get
		{
			return this._adres;
		}
		set
		{
			if ((this._adres != value))
			{
				this.OnadresChanging(value);
				this.SendPropertyChanging();
				this._adres = value;
				this.SendPropertyChanged("adres");
				this.OnadresChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tip", DbType="NVarChar(50)")]
	public string tip
	{
		get
		{
			return this._tip;
		}
		set
		{
			if ((this._tip != value))
			{
				this.OntipChanging(value);
				this.SendPropertyChanging();
				this._tip = value;
				this.SendPropertyChanged("tip");
				this.OntipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durum", DbType="NVarChar(50)")]
	public string durum
	{
		get
		{
			return this._durum;
		}
		set
		{
			if ((this._durum != value))
			{
				this.OndurumChanging(value);
				this.SendPropertyChanging();
				this._durum = value;
				this.SendPropertyChanged("durum");
				this.OndurumChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hareketler")]
public partial class hareketler : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _h_id;
	
	private System.Nullable<int> _mid;
	
	private string _para1;
	
	private string _para2;
	
	private string _aciklama;
	
	private System.Nullable<System.DateTime> _tarih;
	
	private string _hno;
	
	private string _hno2;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onh_idChanging(int value);
    partial void Onh_idChanged();
    partial void OnmidChanging(System.Nullable<int> value);
    partial void OnmidChanged();
    partial void Onpara1Changing(string value);
    partial void Onpara1Changed();
    partial void Onpara2Changing(string value);
    partial void Onpara2Changed();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OntarihChanging(System.Nullable<System.DateTime> value);
    partial void OntarihChanged();
    partial void OnhnoChanging(string value);
    partial void OnhnoChanged();
    partial void Onhno2Changing(string value);
    partial void Onhno2Changed();
    #endregion
	
	public hareketler()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int h_id
	{
		get
		{
			return this._h_id;
		}
		set
		{
			if ((this._h_id != value))
			{
				this.Onh_idChanging(value);
				this.SendPropertyChanging();
				this._h_id = value;
				this.SendPropertyChanged("h_id");
				this.Onh_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mid", DbType="Int")]
	public System.Nullable<int> mid
	{
		get
		{
			return this._mid;
		}
		set
		{
			if ((this._mid != value))
			{
				this.OnmidChanging(value);
				this.SendPropertyChanging();
				this._mid = value;
				this.SendPropertyChanged("mid");
				this.OnmidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_para1", DbType="NChar(10)")]
	public string para1
	{
		get
		{
			return this._para1;
		}
		set
		{
			if ((this._para1 != value))
			{
				this.Onpara1Changing(value);
				this.SendPropertyChanging();
				this._para1 = value;
				this.SendPropertyChanged("para1");
				this.Onpara1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_para2", DbType="NChar(10)")]
	public string para2
	{
		get
		{
			return this._para2;
		}
		set
		{
			if ((this._para2 != value))
			{
				this.Onpara2Changing(value);
				this.SendPropertyChanging();
				this._para2 = value;
				this.SendPropertyChanged("para2");
				this.Onpara2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="NVarChar(150)")]
	public string aciklama
	{
		get
		{
			return this._aciklama;
		}
		set
		{
			if ((this._aciklama != value))
			{
				this.OnaciklamaChanging(value);
				this.SendPropertyChanging();
				this._aciklama = value;
				this.SendPropertyChanged("aciklama");
				this.OnaciklamaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="DateTime")]
	public System.Nullable<System.DateTime> tarih
	{
		get
		{
			return this._tarih;
		}
		set
		{
			if ((this._tarih != value))
			{
				this.OntarihChanging(value);
				this.SendPropertyChanging();
				this._tarih = value;
				this.SendPropertyChanged("tarih");
				this.OntarihChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hno", DbType="NVarChar(50)")]
	public string hno
	{
		get
		{
			return this._hno;
		}
		set
		{
			if ((this._hno != value))
			{
				this.OnhnoChanging(value);
				this.SendPropertyChanging();
				this._hno = value;
				this.SendPropertyChanged("hno");
				this.OnhnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hno2", DbType="NVarChar(50)")]
	public string hno2
	{
		get
		{
			return this._hno2;
		}
		set
		{
			if ((this._hno2 != value))
			{
				this.Onhno2Changing(value);
				this.SendPropertyChanging();
				this._hno2 = value;
				this.SendPropertyChanged("hno2");
				this.Onhno2Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.iletisim_formu_mesajlari")]
public partial class iletisim_formu_mesajlari : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _mesaj_id;
	
	private string _adsoyad;
	
	private string _mesaj;
	
	private System.Nullable<System.DateTime> _tarih;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmesaj_idChanging(int value);
    partial void Onmesaj_idChanged();
    partial void OnadsoyadChanging(string value);
    partial void OnadsoyadChanged();
    partial void OnmesajChanging(string value);
    partial void OnmesajChanged();
    partial void OntarihChanging(System.Nullable<System.DateTime> value);
    partial void OntarihChanged();
    #endregion
	
	public iletisim_formu_mesajlari()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesaj_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int mesaj_id
	{
		get
		{
			return this._mesaj_id;
		}
		set
		{
			if ((this._mesaj_id != value))
			{
				this.Onmesaj_idChanging(value);
				this.SendPropertyChanging();
				this._mesaj_id = value;
				this.SendPropertyChanged("mesaj_id");
				this.Onmesaj_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adsoyad", DbType="NVarChar(50)")]
	public string adsoyad
	{
		get
		{
			return this._adsoyad;
		}
		set
		{
			if ((this._adsoyad != value))
			{
				this.OnadsoyadChanging(value);
				this.SendPropertyChanging();
				this._adsoyad = value;
				this.SendPropertyChanged("adsoyad");
				this.OnadsoyadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesaj", DbType="NVarChar(MAX)")]
	public string mesaj
	{
		get
		{
			return this._mesaj;
		}
		set
		{
			if ((this._mesaj != value))
			{
				this.OnmesajChanging(value);
				this.SendPropertyChanging();
				this._mesaj = value;
				this.SendPropertyChanged("mesaj");
				this.OnmesajChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="Date")]
	public System.Nullable<System.DateTime> tarih
	{
		get
		{
			return this._tarih;
		}
		set
		{
			if ((this._tarih != value))
			{
				this.OntarihChanging(value);
				this.SendPropertyChanging();
				this._tarih = value;
				this.SendPropertyChanged("tarih");
				this.OntarihChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ayarlar")]
public partial class ayarlar : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _hno;
	
	private System.Nullable<int> _ip_dogrula;
	
	private System.Nullable<int> _mail_dogrula;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhnoChanging(string value);
    partial void OnhnoChanged();
    partial void Onip_dogrulaChanging(System.Nullable<int> value);
    partial void Onip_dogrulaChanged();
    partial void Onmail_dogrulaChanging(System.Nullable<int> value);
    partial void Onmail_dogrulaChanged();
    #endregion
	
	public ayarlar()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hno", DbType="NVarChar(50)")]
	public string hno
	{
		get
		{
			return this._hno;
		}
		set
		{
			if ((this._hno != value))
			{
				this.OnhnoChanging(value);
				this.SendPropertyChanging();
				this._hno = value;
				this.SendPropertyChanged("hno");
				this.OnhnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_dogrula", DbType="Int")]
	public System.Nullable<int> ip_dogrula
	{
		get
		{
			return this._ip_dogrula;
		}
		set
		{
			if ((this._ip_dogrula != value))
			{
				this.Onip_dogrulaChanging(value);
				this.SendPropertyChanging();
				this._ip_dogrula = value;
				this.SendPropertyChanged("ip_dogrula");
				this.Onip_dogrulaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail_dogrula", DbType="Int")]
	public System.Nullable<int> mail_dogrula
	{
		get
		{
			return this._mail_dogrula;
		}
		set
		{
			if ((this._mail_dogrula != value))
			{
				this.Onmail_dogrulaChanging(value);
				this.SendPropertyChanging();
				this._mail_dogrula = value;
				this.SendPropertyChanged("mail_dogrula");
				this.Onmail_dogrulaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IP")]
public partial class IP : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _hno;
	
	private string _IP1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhnoChanging(string value);
    partial void OnhnoChanged();
    partial void OnIP1Changing(string value);
    partial void OnIP1Changed();
    #endregion
	
	public IP()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hno", DbType="NVarChar(50)")]
	public string hno
	{
		get
		{
			return this._hno;
		}
		set
		{
			if ((this._hno != value))
			{
				this.OnhnoChanging(value);
				this.SendPropertyChanging();
				this._hno = value;
				this.SendPropertyChanged("hno");
				this.OnhnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="IP", Storage="_IP1", DbType="NVarChar(50)")]
	public string IP1
	{
		get
		{
			return this._IP1;
		}
		set
		{
			if ((this._IP1 != value))
			{
				this.OnIP1Changing(value);
				this.SendPropertyChanging();
				this._IP1 = value;
				this.SendPropertyChanged("IP1");
				this.OnIP1Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.girisler")]
public partial class girisler : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _hno;
	
	private string _tarih;
	
	private string _tarayici_bilgisi;
	
	private string _IP;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhnoChanging(string value);
    partial void OnhnoChanged();
    partial void OntarihChanging(string value);
    partial void OntarihChanged();
    partial void Ontarayici_bilgisiChanging(string value);
    partial void Ontarayici_bilgisiChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    #endregion
	
	public girisler()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hno", DbType="NVarChar(30)")]
	public string hno
	{
		get
		{
			return this._hno;
		}
		set
		{
			if ((this._hno != value))
			{
				this.OnhnoChanging(value);
				this.SendPropertyChanging();
				this._hno = value;
				this.SendPropertyChanged("hno");
				this.OnhnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="NVarChar(50)")]
	public string tarih
	{
		get
		{
			return this._tarih;
		}
		set
		{
			if ((this._tarih != value))
			{
				this.OntarihChanging(value);
				this.SendPropertyChanging();
				this._tarih = value;
				this.SendPropertyChanged("tarih");
				this.OntarihChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarayici_bilgisi", DbType="NVarChar(100)")]
	public string tarayici_bilgisi
	{
		get
		{
			return this._tarayici_bilgisi;
		}
		set
		{
			if ((this._tarayici_bilgisi != value))
			{
				this.Ontarayici_bilgisiChanging(value);
				this.SendPropertyChanging();
				this._tarayici_bilgisi = value;
				this.SendPropertyChanged("tarayici_bilgisi");
				this.Ontarayici_bilgisiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="NVarChar(100)")]
	public string IP
	{
		get
		{
			return this._IP;
		}
		set
		{
			if ((this._IP != value))
			{
				this.OnIPChanging(value);
				this.SendPropertyChanging();
				this._IP = value;
				this.SendPropertyChanged("IP");
				this.OnIPChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.musteri")]
public partial class musteri : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _mid;
	
	private string _hno;
	
	private string _ad;
	
	private string _soyad;
	
	private string _sifre;
	
	private string _hesap;
	
	private string _email;
	
	private string _adres;
	
	private string _tel;
	
	private string _musteri_tipi;
	
	private string _erisim_hak;
	
	private string _plaka;
	
	private string _firma;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmidChanging(int value);
    partial void OnmidChanged();
    partial void OnhnoChanging(string value);
    partial void OnhnoChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsoyadChanging(string value);
    partial void OnsoyadChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OnhesapChanging(string value);
    partial void OnhesapChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void Onmusteri_tipiChanging(string value);
    partial void Onmusteri_tipiChanged();
    partial void Onerisim_hakChanging(string value);
    partial void Onerisim_hakChanged();
    partial void OnplakaChanging(string value);
    partial void OnplakaChanged();
    partial void OnfirmaChanging(string value);
    partial void OnfirmaChanged();
    #endregion
	
	public musteri()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int mid
	{
		get
		{
			return this._mid;
		}
		set
		{
			if ((this._mid != value))
			{
				this.OnmidChanging(value);
				this.SendPropertyChanging();
				this._mid = value;
				this.SendPropertyChanged("mid");
				this.OnmidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hno", DbType="NVarChar(50)")]
	public string hno
	{
		get
		{
			return this._hno;
		}
		set
		{
			if ((this._hno != value))
			{
				this.OnhnoChanging(value);
				this.SendPropertyChanging();
				this._hno = value;
				this.SendPropertyChanged("hno");
				this.OnhnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50)")]
	public string ad
	{
		get
		{
			return this._ad;
		}
		set
		{
			if ((this._ad != value))
			{
				this.OnadChanging(value);
				this.SendPropertyChanging();
				this._ad = value;
				this.SendPropertyChanged("ad");
				this.OnadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyad", DbType="NVarChar(50)")]
	public string soyad
	{
		get
		{
			return this._soyad;
		}
		set
		{
			if ((this._soyad != value))
			{
				this.OnsoyadChanging(value);
				this.SendPropertyChanging();
				this._soyad = value;
				this.SendPropertyChanged("soyad");
				this.OnsoyadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(32)")]
	public string sifre
	{
		get
		{
			return this._sifre;
		}
		set
		{
			if ((this._sifre != value))
			{
				this.OnsifreChanging(value);
				this.SendPropertyChanging();
				this._sifre = value;
				this.SendPropertyChanged("sifre");
				this.OnsifreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hesap", DbType="NVarChar(50)")]
	public string hesap
	{
		get
		{
			return this._hesap;
		}
		set
		{
			if ((this._hesap != value))
			{
				this.OnhesapChanging(value);
				this.SendPropertyChanging();
				this._hesap = value;
				this.SendPropertyChanged("hesap");
				this.OnhesapChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(50)")]
	public string adres
	{
		get
		{
			return this._adres;
		}
		set
		{
			if ((this._adres != value))
			{
				this.OnadresChanging(value);
				this.SendPropertyChanging();
				this._adres = value;
				this.SendPropertyChanged("adres");
				this.OnadresChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(11)")]
	public string tel
	{
		get
		{
			return this._tel;
		}
		set
		{
			if ((this._tel != value))
			{
				this.OntelChanging(value);
				this.SendPropertyChanging();
				this._tel = value;
				this.SendPropertyChanged("tel");
				this.OntelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteri_tipi", DbType="NChar(10)")]
	public string musteri_tipi
	{
		get
		{
			return this._musteri_tipi;
		}
		set
		{
			if ((this._musteri_tipi != value))
			{
				this.Onmusteri_tipiChanging(value);
				this.SendPropertyChanging();
				this._musteri_tipi = value;
				this.SendPropertyChanged("musteri_tipi");
				this.Onmusteri_tipiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_erisim_hak", DbType="NChar(10)")]
	public string erisim_hak
	{
		get
		{
			return this._erisim_hak;
		}
		set
		{
			if ((this._erisim_hak != value))
			{
				this.Onerisim_hakChanging(value);
				this.SendPropertyChanging();
				this._erisim_hak = value;
				this.SendPropertyChanged("erisim_hak");
				this.Onerisim_hakChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plaka", DbType="VarChar(50)")]
	public string plaka
	{
		get
		{
			return this._plaka;
		}
		set
		{
			if ((this._plaka != value))
			{
				this.OnplakaChanging(value);
				this.SendPropertyChanging();
				this._plaka = value;
				this.SendPropertyChanged("plaka");
				this.OnplakaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma", DbType="VarChar(50)")]
	public string firma
	{
		get
		{
			return this._firma;
		}
		set
		{
			if ((this._firma != value))
			{
				this.OnfirmaChanging(value);
				this.SendPropertyChanging();
				this._firma = value;
				this.SendPropertyChanged("firma");
				this.OnfirmaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
